version: '3.9'

services:
  watcher:
    image: htwberlin/mdwvzaehlerstaende-client-watcher:latest
    build:
      context: watcher
    volumes:
      - /opt/vc:/opt/vc
      - "watchershared:/var/shared_volume"
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
      - SERVER_WEBSERVICE=http://mzdev.talomation.de:5002/
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm
  clientws:
    image: htwberlin/mdwvzaehlerstaende-client-ws:latest
    build:
      context: webservice
    environment:
      - SERVER_WEBSERVICE=http://mzdev.talomation.de:5002/
    ports:
      - "5004:5004"
    volumes:
      - "watchershared:/home/watcher_files"

volumes:
  watchershared: